CREATE TABLE products (
  product_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  category_id INT,
  product_title VARCHAR(255),
  image_url VARCHAR(255),
  sku VARCHAR(255),
  price_unit DECIMAL(7,2),
  quantity INT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
);
